# Generated by Django 4.1.7 on 2023-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet_id', models.PositiveBigIntegerField(unique=True)),
                ('user_name', models.CharField(max_length=256)),
                ('image_url', models.CharField(default='', max_length=256)),
                ('video_url', models.CharField(default='', max_length=256)),
                ('text', models.TextField(max_length=4000)),
                ('handle', models.CharField(max_length=16)),
                ('likes', models.CharField(max_length=16)),
                ('retweets', models.CharField(max_length=16)),
                ('replies', models.CharField(max_length=16)),
                ('views', models.CharField(max_length=16)),
                ('sentiment', models.CharField(max_length=256)),
            ],
        ),
    ]
